### ISSUE TITLE
Pandoc error (MacOS)?

### ISSUE THREAD

**Issue by pioniere** [Linbreux/wikmd#109]
I tried installing wikmd on a MacOS with Python 3.9.2 and Pandoc 3.11, and got the error below. I'm wondering if the problem is because I was using the newest version of pandoc? (I couldn't find any reference to Pandoc or Python versions in the docs) I'm not sure what else it might be. Got this error:

`$ python3 wiki.py

[2023-03-07 18:34:08,508] INFO in git_manager: Initializing existing repo >>> wiki ...
 * Serving Flask app "wiki" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[2023-03-07 18:34:14,037] INFO in wiki: Showing HTML page >>> 'homepage'
[2023-03-07 18:34:14,037] INFO in wiki: Converting to HTML with pandoc >>> 'homepage' ...
[2023-03-07 18:34:16,334] INFO in wiki: Showing HTML page >>> 'homepage'
[2023-03-07 18:34:16,336] INFO in wiki: Converting to HTML with pandoc >>> 'homepage' ...
[2023-03-07 18:34:17,098] ERROR in wiki: Conversion to HTML failed >>> Pandoc died with exitcode "83" during conversion: b'Traceback (most recent call last):\n  File "/Users/this.user/Library/Python/3.9/bin/pandoc-xnos", line 8, in <module>\n    sys.exit(main())\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandocxnos/main.py", line 38, in main\n    m.main(stdin, stdout)\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandoc_fignos.py", line 608, in main\n    PANDOCVERSION = pandocxnos.init(args.pandocversion, doc)\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandocxnos/core.py", line 224, in init\n    _PANDOCVERSION = _get_pandoc_version(pandocversion, doc)\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandocxnos/core.py", line 179, in _get_pandoc_version\n    raise RuntimeError(msg)\nRuntimeError: Cannot understand pandocversion=3.1.1\nError running filter pandoc-xnos:\nFilter returned error status 1\n'
[2023-03-07 18:34:17,830] ERROR in wiki: Conversion to HTML failed >>> Pandoc died with exitcode "83" during conversion: b'Traceback (most recent call last):\n  File "/Users/this.user/Library/Python/3.9/bin/pandoc-xnos", line 8, in <module>\n    sys.exit(main())\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandocxnos/main.py", line 38, in main\n    m.main(stdin, stdout)\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandoc_fignos.py", line 608, in main\n    PANDOCVERSION = pandocxnos.init(args.pandocversion, doc)\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandocxnos/core.py", line 224, in init\n    _PANDOCVERSION = _get_pandoc_version(pandocversion, doc)\n  File "/Users/this.user/Library/Python/3.9/lib/python/site-packages/pandocxnos/core.py", line 179, in _get_pandoc_version\n    raise RuntimeError(msg)\nRuntimeError: Cannot understand pandocversion=3.1.1\nError running filter pandoc-xnos:\nFilter returned error status 1\n'

$ pandoc --version

pandoc 3.1.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/this.user/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

`

**Comment by Linbreux** [comment]
Hi @pioniere 
I'm using pandoc 2.5 for now. But I'll look into upgrading. Does 2.5 work for you?

**Comment by pioniere** [comment]
I wasn't sure which one to try next, but I'll give 2.5 a shot and will let you know. Thanks!

**Comment by pioniere** [comment]
@Linbreux Moving to an older version unfortunately did not fix this. I'm going to have to figure out another solution so I can use my .md files. Thanks for your help, hope to revisit this software again. Feel free to close this, unless you have some other ideas.

**Comment by Linbreux** [comment]
@pioniere couldn't you just use the docker container?
