### ISSUE TITLE
[1.8.2] permission denied on /var/log/wikimd.log

### ISSUE THREAD

**Issue by Arsoth** [Linbreux/wikmd#111]
Hey, this works great on 1.8.1, but I spent around 2 hours trying to fix the latest version of 1.8.2 before I tried rolling back to see if it was a version issue.

Environment: 
Docker 23.0.1
Debian Bullseye

I was using the correct user and group settings as well.

```[2023-03-24 22:24:34,776] INFO in git_manager: Initializing existing repo >>> /wiki ...
[2023-03-24 22:24:34,788] INFO in image_manager: Checking if webp is available for image optimization ...
sh: 1: cwebp: not found
Traceback (most recent call last):
DrawIO integration
Alerts system
Mermaid integration
  File "/app/wikmd/wiki.py", line 465, in <module>
    run_wiki()
  File "/app/wikmd/wiki.py", line 450, in run_wiki
    logging.basicConfig(filename=cfg.wikmd_logging_file, level=logging.INFO)
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: '/var/log/wikmd.log'```

**Comment by Linbreux** [comment]
Hi @Arsoth,
That should have never made it in a stable release, thanks for noticing. I guess this happened by upgrading the ubuntu version... 600c69ba37c5c6b8ac87ae97953840d79fa096bd fixes this. But there is still a problem with the plugins folder when you run the wiki for the first time, i'm trying to solve that.

**Comment by tbnguyen1407** [comment]
@Linbreux you probably need to fix other places as well. Enabling local mode also throws error in docker:

## reproduction

```
## compose.yaml
services:
  wiki:
    image: docker.io/linbreux/wikmd:v1.8.3
    environment:
      PGID: "1000"
      PUID: "1000"
      LOCAL_MODE: true
```

## output

```
[2023-05-24 02:52:18,149] INFO in web_dependencies: Downloading dependency https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css
[2023-05-24 02:52:18,279] INFO in web_dependencies: Writing dependency >>> /app/wikmd/static/css/bootstrap.min.css
Traceback (most recent call last):
   File "/app/wikmd/wiki.py", line 44, in <module>
     web_deps = get_web_deps(cfg.local_mode, app.logger)
   File "/app/wikmd/web_dependencies.py", line 94, in get_web_deps
     download_web_deps(logger)
   File "/app/wikmd/web_dependencies.py", line 116, in download_web_deps
     with open(dep_file_path, "wb") as file:
PermissionError: [Errno 13] Permission denied: '/app/wikmd/static/css/bootstrap.min.css'
```

**Comment by Linbreux** [comment]
Hi @tbnguyen1407 

Thanks for letting me know! I'll implement it in the next release.

If there is something else happening in the docker, feel free to create an issue!

**Comment by Linbreux** [comment]
@tbnguyen1407 Could you try the docker `edge` tag?

**Comment by tbnguyen1407** [comment]
@Linbreux Thanks. `edge` tag no longer crashes with permission error.
