### ISSUE TITLE
Permission issues from draw plugin

### ISSUE THREAD

**Issue by spectraldecomp** [Linbreux/wikmd#124]
Hello,

Running wikmd on Windows 11 but via docker-compose.

Here is my `docker-compose.yml`: 
````
---
version: "2.1"
services:
  wikmd:
    image: linbreux/wikmd:latest
    container_name: wikmd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./wiki:/wiki
    ports:
      - 5000:5000
    restart: unless-stopped
````

After `docker-compose up --build` from wikmd, the website runs but gives the following errors when I try to edit, create, or delete any page: 
````
wikmd  | Traceback (most recent call last):
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2464, in __call__
wikmd  |     return self.wsgi_app(environ, start_response)
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2450, in wsgi_app
wikmd  |     response = self.handle_exception(e)
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1867, in handle_exception
wikmd  |     reraise(exc_type, exc_value, tb)
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/_compat.py", line 39, in reraise
wikmd  |     raise value
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2447, in wsgi_app
wikmd  |     response = self.full_dispatch_request()
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1952, in full_dispatch_request
wikmd  |     rv = self.handle_user_exception(e)
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1821, in handle_user_exception
wikmd  |     reraise(exc_type, exc_value, tb)
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/_compat.py", line 39, in reraise
wikmd  |     raise value
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1950, in full_dispatch_request
wikmd  |     rv = self.dispatch_request()
wikmd  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1936, in dispatch_request
wikmd  |     return self.view_functions[rule.endpoint](**req.view_args)
wikmd  |   File "/app/wikmd/wiki.py", line 293, in edit_homepage
wikmd  |     save(page_name)
wikmd  |   File "/app/wikmd/wiki.py", line 86, in save
wikmd  |     content = process(request.form['CT'], page_name)
wikmd  |   File "/app/wikmd/wiki.py", line 76, in process
wikmd  |     processed = plugin.process_md(processed)
wikmd  |   File "/app/wikmd/plugins/draw/draw.py", line 30, in process_md
wikmd  |     return self.search_for_pattern_and_replace_with_uniqueid(md)
wikmd  |   File "/app/wikmd/plugins/draw/draw.py", line 88, in search_for_pattern_and_replace_with_uniqueid
wikmd  |     self.create_draw_file(filename)
wikmd  |   File "/app/wikmd/plugins/draw/draw.py", line 72, in create_draw_file
wikmd  |     shutil.copyfile(os.path.join(self.this_location, "default_draw"), path_to_file)
wikmd  |   File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
wikmd  |     with open(dst, 'wb') as fdst:
wikmd  | PermissionError: [Errno 13] Permission denied: '/app/wikmd/plugins/draw/drawings/draw_0a852367-cdac-4a8b-a458-87dbdc67563d'
````

Strangely, after rerunning the docker container, editing works fine. It is only the first time that an error appears?

**Comment by spectraldecomp** [comment]
I was able to fix this by having basic docker knowledge.

**Comment by ammacdonald3** [comment]
What did you do to fix it? I'm seeing the same error when trying to save a page.
