### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by tyeeman** [Linbreux/wikmd#176]
I ran the ```pip install wikmd``` install command and got no errors. I then ran ```python -m wikmd.wiki``` to start the server and got the following git error.

```
g:\wikmd>python -m wikmd.wiki
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\git\__init__.py", line 140, in <module>
    refresh()
  File "C:\Program Files\Python312\Lib\site-packages\git\__init__.py", line 127, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\git\cmd.py", line 455, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logged at level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Lib\site-packages\wikmd\wiki.py", line 29, in <module>
    from wikmd.git_manager import WikiRepoManager
  File "C:\Program Files\Python312\Lib\site-packages\wikmd\git_manager.py", line 6, in <module>
    from git import GitCommandError, InvalidGitRepositoryError, NoSuchPathError, Repo
  File "C:\Program Files\Python312\Lib\site-packages\git\__init__.py", line 142, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logged at level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Comment by tyeeman** [comment]
OK, I installed git and it seems to be working but localhost url is not in the docs.

**Comment by Linbreux** [comment]
@tyeeman Could you check the latest version of wikmd on pypi using pip? 81c7d086268 should fix this.

**Comment by tyeeman** [comment]
Yes, it works, thanks.
