### ISSUE TITLE
Exception for custom wiki directory

### ISSUE THREAD

**Issue by Mik3Rizzo** [Linbreux/wikmd#36]
I set up `wiki_directory = "m-iki"` and I got this exception:

```
Traceback (most recent call last):
  File "/opt/wikmd/wiki.py", line 39, in <module>
    wrm = WikiRepoManager(flask_app=app)
  File "/opt/wikmd/git_manager.py", line 45, in __init__
    self.__git_repo_init()
  File "/opt/wikmd/git_manager.py", line 55, in __git_repo_init
    self.__init_remote_repo()
  File "/opt/wikmd/git_manager.py", line 88, in __init_remote_repo
    if os.listdir(self.wiki_directory):
FileNotFoundError: [Errno 2] No such file or directory: 'm-iki'
```

**Comment by Linbreux** [comment]
Did you also make the directory?

**Comment by Mik3Rizzo** [comment]
> Did you also make the directory?

No! If you manually make the directory, the exception doesn't occur.
I expected that the software makes the directory if it doesn't exist. Maybe we should add that.

**Comment by Linbreux** [comment]
hi @Mik3Rizzo 
I tried this, and in my case it creates the correct folder automatically. Could you give a little more detail?

**Comment by Mik3Rizzo** [comment]
> Could you give a little more detail?

What I did (on Windows 10):
- clone a fresh linbreux/wikmd repo
- change the `yaml` with
```
sync_with_remote: 1                                                                                                                                 remote_url: "https://github.com/Mik3Rizzo/m-iki.git"                                                                                                wiki_directory: "m-iki" 
```

What I got:
```
(venv) PS C:\Users\mrizz\Desktop\Workspaces\test\wikmd> python wiki.py
[2022-04-08 11:46:09,931] INFO in git_manager: Cloning >>> https://github.com/Mik3Rizzo/m-iki.git ...
Traceback (most recent call last):
  File "C:\Users\mrizz\Desktop\Workspaces\test\wikmd\wiki.py", line 39, in <module>
    wrm = WikiRepoManager(flask_app=app)
  File "C:\Users\mrizz\Desktop\Workspaces\test\wikmd\git_manager.py", line 45, in __init__
    self.__git_repo_init()
  File "C:\Users\mrizz\Desktop\Workspaces\test\wikmd\git_manager.py", line 55, in __git_repo_init
    self.__init_remote_repo()
  File "C:\Users\mrizz\Desktop\Workspaces\test\wikmd\git_manager.py", line 88, in __init_remote_repo
    if os.listdir(self.wiki_directory):
FileNotFoundError: [WinError 3] Impossibile trovare il percorso specificato: 'm-iki'
```

It can be a Windows related error, I'll try it on Debian.

**Comment by Mik3Rizzo** [comment]
> Can you test the branch [gitmanager_folder_create](https://github.com/Linbreux/wikmd/tree/gitmanager_folder_create), to see if the problem is solved?

Works both on Win and on Raspberry OS. Nice!

**Comment by Linbreux** [comment]
alright, I merged it!
