### ISSUE TITLE
PermissionError with default config

### ISSUE THREAD

**Issue by goliath888** [Linbreux/wikmd#90]
I just spin up a docker container as basic as it can be. 

```
version: "2.1"
services:
  wikmd:
    image: linbreux/wikmd:latest
    container_name: wikmd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 5000:5000
    restart: unless-stopped
```

I start the application and the default page is shown, but if I try to edit it or create a new one I am having this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/wikmd/wiki.py", line 272, in edit_homepage
    save(page_name)
  File "/app/wikmd/wiki.py", line 66, in save
    content = plugin.process_md(content)
  File "/app/wikmd/plugins/draw/draw.py", line 26, in process_md
    return self.search_for_pattern_and_replace_with_uniqueid(md)
  File "/app/wikmd/plugins/draw/draw.py", line 83, in search_for_pattern_and_replace_with_uniqueid
    self.create_draw_file(filename)
  File "/app/wikmd/plugins/draw/draw.py", line 68, in create_draw_file
    shutil.copyfile(os.path.join(self.this_location, "default_draw"), path_to_file)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/app/wikmd/plugins/draw/drawings/draw_e03c70da-ab4a-4c53-bbe4-ead5a7fa36ee'
```

Maybe something related with permissions on /app/wikmd/ path?

**Comment by Linbreux** [comment]
Hi @goliath888,
Thanks for letting me know. After implementing the new plugin system there were some permissions problems in the docker images. eba81bbaafdbdab478e3ada76937f64973c86578 should fix this. 
You should be able to pull the latest docker image now. Let me know if there is something else.

**Comment by goliath888** [comment]
Yes, it is working perfectly now, thanks.
