### ISSUE TITLE
Permissions issue in MacOS

### ISSUE THREAD

**Issue by pioniere** [Linbreux/wikmd#91]
Using wikmd in MacOS. The previous version of wikmd worked perfectly. This new version however will not start, throwing the following error:

```
Initializing existing repo >>> wiki ...
DrawIO integration
Alerts system
Traceback (most recent call last):
  File "wiki.py", line 52, in <module>
    cache = Cache(cfg.cache_dir)
  File "/Users/jeff/Development/Python/wikmd/cache.py", line 14, in __init__
    os.makedirs(path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/dev/shm' 
```

Any suggestions? Thanks!

**Comment by Linbreux** [comment]
hi @pioniere,
It seems like you don't have the right permissions for the `/dev/shm` folder. If you don't want to change the permission, you can change the folder where the `cache` and `search` are stored. 
Just change them in `wikmd-config.yaml`.

Example:
create 2 folders in a location were you have permission
```
mkdir

**Comment by pioniere** [comment]
Thanks, that fixed it.

**Comment by vbuell** [comment]
I guess this may be quite a common issue. Should the workaround be documented somewhere (Installation page)?

**Comment by Linbreux** [comment]
@vbuell Did not know this was that common. Of course you can create a PR if you want ;)
